version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: test
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - "8082:80"
    depends_on:
      - mysql
    volumes:
      - phpmyadmin-data:/var/www/html

volumes:
  mysql-data:
  phpmyadmin-data: